title: The End
author: Waveshocked
email: waveshocked@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In order to assist with the understanding of what is being told, is 
  erase all prior thinking.

# social links
twitter_username: Granpapi
github_username:  Waveshocked

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
